const frasesMotivacionais = [
    "💪 Vai com tudo, porque você é incrível! 💥",
    "😎 A vida é curta, então seja você mesmo e brilhe! ✨",
    "🚀 Acredite em si mesmo, você é um campeão! 🏆",
    "🌈 Não deixe ninguém apagar seu arco-íris! 🌟",
    "🙌 Você é capaz de coisas incríveis, acredite nisso! 🌠",
    "🤗 Abraça o dia com um sorriso e conquiste o mundo! 😃",
    "🏁 Você está mais perto do sucesso do que imagina! 🏁",
    "🎉 A vida é uma aventura, aproveite cada momento! 🌄",
    "🌟 O poder está dentro de você, use-o! 💫",
    "💃 Dance na chuva e celebre a vida! ☔",
    "🚀 O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "🌈 Sonhe grande e ouse falhar.",
    "🔥 O sucesso é a melhor vingança.",
    "🌞 Um dia de cada vez. Você consegue!",
    "🌴 Mantenha a calma e continue avançando.",
    "💡 Seja a luz que guia os outros.",
    "💫 Seja você mesmo; todos os outros já existem.",
    "🍀 A sorte favorece os corajosos.",
    "🌻 Acredite que você pode e você já está no meio do caminho.",
    "🌠 O impossível só leva um pouco mais de tempo.",
    "📚 A educação é a chave para o sucesso.",
    "💡 A criatividade é contagiosa, passe adiante.",
    "💡 Não é sobre quantas vezes você cai, mas quantas vezes você se levanta.",
    "🎓 Aprenda algo novo todos os dias.",
    "🏆 O talento ganha jogos, mas o trabalho em equipe e a inteligência ganham campeonatos.",
    "🌧️ A chuva é apenas confete do céu.",
    "🚢 O melhor momento para começar é agora.",
    "🌊 Navegue em direção aos seus sonhos.",
    "🏋️‍♀️ Não pare até se orgulhar.",
    "🌄 Cada novo dia é uma nova oportunidade.",
    "💪 Você é mais forte do que imagina.",
    "🌍 O mundo é o seu playground.",
    "🧠 A mente é tudo. O que você pensa, você se torna.",
    "💥 Seja lendário.",
    "🤩 Viva a vida com paixão.",
    "🤗 Sorria, você está fazendo a diferença.",
    "🌅 O amanhã é uma página em branco; escreva uma história incrível.",
    "🌻 A vida é uma aventura, então aproveite o passeio.",
    "🙌 As coisas boas estão a caminho.",
    "🔑 A chave para o sucesso está em você.",
    "🎉 Celebre as pequenas vitórias.",
    "⏳ O tempo é o recurso mais valioso; use-o sabiamente.",
    "💓 Ame o que você faz e faça o que você ama.",
    "🚴‍♀️ Continue pedalando, mesmo quando a estrada fica íngreme.",
    "🌟 Você é a estrela do seu próprio show.",
    "🏆 Você é um vencedor!",
    "💪 Persistência supera resistência.",
    "🌈 Cada dia é uma nova oportunidade para brilhar.",
    "🌟 Seja a melhor versão de você mesmo.",
    "📈 Siga em frente e continue subindo.",
    "🏝️ Relaxe, respire fundo e siga em frente.",
    "🎁 O presente é um presente; aproveite-o ao máximo.",
    "👍 Você está no caminho certo!",
    "🌞 O sol sempre brilha depois da tempestade.",
    "💡 A vida é uma jornada; aproveite o passeio!",
    "🌟 Você é incrível exatamente como é.",
    "🚀 Acredite em si mesmo, você é capaz de coisas incríveis! 💪",
    "😄 Sorria, você é a luz do seu próprio dia! 🌞",
    "💡 Cada desafio é uma oportunidade de crescimento. 🌱",
    "🌟 Seja a estrela que brilha na sua história! ✨",
    "🎯 Sonhe grande, alcance alto e nunca desista! 🏆",
    "🌈 A vida é uma tela em branco, pinte-a com cores vibrantes! 🎨",
    "🏁 Não importa o quão devagar você vá, desde que você não pare! 🏃‍♀️",
    "🚢 Navegue pelos ventos da mudança com confiança! ⛵",
    "🎉 Celebre as pequenas vitórias na jornada para o sucesso! 🎈",
    "🌞 Cada dia é uma página em branco, escreva uma história incrível! 📖",
    "🔑 Você detém a chave para desbloquear seu potencial ilimitado! 🗝️",
    "🏆 Lembre-se de que vencer é uma questão de atitude! 🥇",
    "🌷 A paciência é a chave para alcançar a mais bela das flores! 🌼",
    "🤗 Compartilhe amor e bondade sempre que possível! ❤️",
    "🏋️‍♂️ O sucesso não é uma linha reta, mas uma série de elevações e quedas. 🏔️",
    "🌊 Enfrente as ondas da vida com coragem e determinação! 🌊",
    "💓 Deixe seu coração ser seu guia e a bússola para a felicidade. 🧭",
    "🌆 O pôr do sol marca o fim de um dia, mas o início de novas possibilidades. 🌇",
    "🧘‍♀️ Acalme sua mente e encontre serenidade no caos. ☮️",
    "🌠 Você é a autora de sua própria história, faça cada capítulo valer a pena! 📚",
    "🍃 Deixe suas preocupações voarem como folhas ao vento. 🍂",
    "🚴‍♂️ Continue pedalando, a vista lá de cima é incrível! 🚵‍♀️",
    "🌏 Respeite o planeta, ele é a única casa que temos. 🌍",
    "🌻 A gratidão transforma o que temos em o suficiente. 🙏",
    "🍀 A sorte sorri para aqueles que trabalham duro. 🍀",
    "🌆 A cidade adormece, mas seus sonhos nunca descansam. 🏙️",
    "💫 Seja a razão do brilho nos olhos de alguém hoje! ✨",
    "🧡 Deixe o amor guiar cada passo que você dá. 💞",
    "🏝️ O destino é apenas uma desculpa para começar uma jornada. 🌄",
    "🤔 Acredite que você pode e você já está a meio caminho lá! 🌟",
    "🌄 Apenas aja e a inspiração o encontrará no caminho! 🚶‍♂️",
    "🚁 Levante voo e alcance alturas inimagináveis! 🌄",
    "🔗 Lembre-se, o futuro é construído com os tijolos do presente. 🧱",
    "🌞 Deixe o brilho do sol aquecer sua alma. ☀️",
    "💪 A força interior é sua maior vantagem. 🦾",
    "🛤️ Siga em frente, cada passo o levará mais perto de seus objetivos. 🚶‍♀️",
    "🌴 Relaxe, respire e aproveite o momento presente. 🌴",
    "🌆 As estrelas brilham mais forte na escuridão. 🌠",
    "🛫 Os sonhos são asas que o levam a lugares distantes. ✈️",
    "🏹 Aponte para a lua, mesmo que você erre, estará entre as estrelas. 🌛",
    "📆 Cada novo dia é uma nova chance de recomeçar. 🆕",
    "🗺️ A vida é uma aventura, explore-a com entusiasmo! 🌍",
    "🧡 A beleza da vida está nas pequenas coisas. 🌼",
    "💗 Seja gentil, pois todos estão travando uma batalha que você não conhece. 🤝",
    "🗝️ Encontre a chave para a felicidade dentro de você. ❤️",
    "🏡 Sua casa é onde seu coração encontra paz. 🏡",
    "🌅 Cada pôr do sol é uma lição sobre deixar ir. 🌇"
  ];
  
  module.exports = frasesMotivacionais;
  